language: node_js
node_js:
  - "12"

branches:
  only:
    - main

addons:
  ssh_known_hosts:
    - 208.68.39.96

cache:
  directories:
    - server/node_modules/.cache/mongodb-memory-server

script:
  - cd client/
  - npm install
  - npm run build
  - cd ../server/
  - npm install
  - npm test
  - cd ../

before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh $USER@$IP_ADDRESS "./deploy_react_node_chat.sh"
  on:
    branch: main